-- BOARD TABLE 생성 --
CREATE TABLE BOARD(
	IDX INT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(100) NOT NULL,
	CONTENT VARCHAR(2000) NOT NULL,
	WRITER VARCHAR(30) NOT NULL,
	INDATE DATETIME DEFAULT NOW(),
	COUNT INT DEFAULT 0,
	PRIMARY KEY(IDX)
);

INSERT INTO BOARD(TITLE, CONTENT,WRITER)
VALUES('오늘은 화요일','내일은 수요일이지','요일박사');
INSERT INTO BOARD(TITLE, CONTENT,WRITER)
VALUES('빅분기 시험','하지만 공부 안했지','뽀로로');
INSERT INTO BOARD(TITLE, CONTENT,WRITER)
VALUES('튀김족발','은 어떤 맛일까','쩝쩝박사');
INSERT INTO BOARD(TITLE, CONTENT,WRITER)
VALUES('데이터분석','은 어려워','D린이');
INSERT INTO BOARD(TITLE, CONTENT,WRITER)
VALUES('이거는','몇개까지 만들어야하나','12345');

COMMIT;

SELECT * FROM BOARD;